[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scrapetools"
version = "0.0.6"
requires-python = ">=3.10"
dependencies = ["bs4","phonenumbers","progbar"]